name: publish to nuget
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        #with:
          #source-url: https://nuget.pkg.github.com/<organization>/index.json
        #env:
          #NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}

      - name: Version
        run: |
          export package_version="0.1.$((${{github.run_number}}-1))"
          echo "Package Version = $package_version"
          echo "package_version=$package_version" >> $GITHUB_ENV
      
      - name: Pack FFMpegInstaller.Windows.x64
        run: |
          dotnet pack FFMpegInstaller.csproj \
          -o _out \
          -c Release \
          -p:PackageVersion=${{env.package_version}} \
          
      - name: Publish FFMpegInstaller.Windows.x64
        run: |
          dotnet nuget push \
          ./_out/FFMpegInstaller.Windows.x64.${{env.package_version}}.nupkg \
          -k ${{secrets.NUGET_KEY}} \
          -s https://api.nuget.org/v3/index.json